package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CaseStudy generated by hbm2java
 */
public class CaseStudy  implements java.io.Serializable {


     private Integer caseStudyId;
     private String caseStudyName;
     private Set<DetectionStudy> detectionStudies = new HashSet<DetectionStudy>(0);

    public CaseStudy() {
    }

	
    public CaseStudy(String caseStudyName) {
        this.caseStudyName = caseStudyName;
    }
    public CaseStudy(String caseStudyName, Set<DetectionStudy> detectionStudies) {
       this.caseStudyName = caseStudyName;
       this.detectionStudies = detectionStudies;
    }
   
    public Integer getCaseStudyId() {
        return this.caseStudyId;
    }
    
    public void setCaseStudyId(Integer caseStudyId) {
        this.caseStudyId = caseStudyId;
    }
    public String getCaseStudyName() {
        return this.caseStudyName;
    }
    
    public void setCaseStudyName(String caseStudyName) {
        this.caseStudyName = caseStudyName;
    }
    public Set<DetectionStudy> getDetectionStudies() {
        return this.detectionStudies;
    }
    
    public void setDetectionStudies(Set<DetectionStudy> detectionStudies) {
        this.detectionStudies = detectionStudies;
    }




}


