package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer categoryId;
     private String categoryTitle;
     private Set<PriceList> priceLists = new HashSet<PriceList>(0);
     private Set<Quest> quests = new HashSet<Quest>(0);
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public Category() {
    }

	
    public Category(String categoryTitle) {
        this.categoryTitle = categoryTitle;
    }
    public Category(String categoryTitle, Set<PriceList> priceLists, Set<Quest> quests, Set<Reservation> reservations) {
       this.categoryTitle = categoryTitle;
       this.priceLists = priceLists;
       this.quests = quests;
       this.reservations = reservations;
    }
   
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryTitle() {
        return this.categoryTitle;
    }
    
    public void setCategoryTitle(String categoryTitle) {
        this.categoryTitle = categoryTitle;
    }
    public Set<PriceList> getPriceLists() {
        return this.priceLists;
    }
    
    public void setPriceLists(Set<PriceList> priceLists) {
        this.priceLists = priceLists;
    }
    public Set<Quest> getQuests() {
        return this.quests;
    }
    
    public void setQuests(Set<Quest> quests) {
        this.quests = quests;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


