package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Concentration generated by hbm2java
 */
public class Concentration  implements java.io.Serializable {


     private Integer concentrationId;
     private String concentrationName;
     private Set<Prescription> prescriptions = new HashSet<Prescription>(0);

    public Concentration() {
    }

	
    public Concentration(String concentrationName) {
        this.concentrationName = concentrationName;
    }
    public Concentration(String concentrationName, Set<Prescription> prescriptions) {
       this.concentrationName = concentrationName;
       this.prescriptions = prescriptions;
    }
   
    public Integer getConcentrationId() {
        return this.concentrationId;
    }
    
    public void setConcentrationId(Integer concentrationId) {
        this.concentrationId = concentrationId;
    }
    public String getConcentrationName() {
        return this.concentrationName;
    }
    
    public void setConcentrationName(String concentrationName) {
        this.concentrationName = concentrationName;
    }
    public Set<Prescription> getPrescriptions() {
        return this.prescriptions;
    }
    
    public void setPrescriptions(Set<Prescription> prescriptions) {
        this.prescriptions = prescriptions;
    }




}


