package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Detection generated by hbm2java
 */
public class Detection implements java.io.Serializable {

    private Integer detectionId;
    private Patient patient;
    private String note;
    private Double extraFees;
    private boolean archive;
    private Date archiveDate;
    private Double discountAmount;
    private User doctor;
    private Set<DetectionSession> sessions = new HashSet<DetectionSession>(0);
    private Set<DetectionStudy> detectionStudies = new HashSet<DetectionStudy>(0);
    private Set<Prescription> prescriptions = new HashSet<Prescription>(0);

    public Detection() {
    }

    public Detection(Patient patient, boolean archive) {
        this.patient = patient;
        this.archive = archive;
    }

    public Detection(Patient patient, String note, Double extraFees, boolean archive, Date archiveDate, Double discountAmount, User doctor, Set<DetectionSession> sessions, Set<DetectionStudy> detectionStudies, Set<Prescription> prescriptions) {
        this.patient = patient;
        this.note = note;
        this.extraFees = extraFees;
        this.archive = archive;
        this.archiveDate = archiveDate;
        this.discountAmount = discountAmount;
        this.doctor = doctor;
        this.sessions = sessions;
        this.detectionStudies = detectionStudies;
        this.prescriptions = prescriptions;
    }

    public Integer getDetectionId() {
        return this.detectionId;
    }

    public void setDetectionId(Integer detectionId) {
        this.detectionId = detectionId;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public Double getExtraFees() {
        return this.extraFees;
    }

    public void setExtraFees(Double extraFees) {
        this.extraFees = extraFees;
    }

    public boolean isArchive() {
        return archive;
    }

    public void setArchive(boolean archive) {
        this.archive = archive;
    }

    public Date getArchiveDate() {
        return this.archiveDate;
    }

    public void setArchiveDate(Date archiveDate) {
        this.archiveDate = archiveDate;
    }

    public Double getDiscountAmount() {
        return this.discountAmount;
    }

    public void setDiscountAmount(Double discountAmount) {
        this.discountAmount = discountAmount;
    }

    public Set<DetectionSession> getSessions() {
        return this.sessions;
    }

    public void setSessions(Set<DetectionSession> sessions) {
        this.sessions = sessions;
    }

    public Set<DetectionStudy> getDetectionStudies() {
        return this.detectionStudies;
    }

    public void setDetectionStudies(Set<DetectionStudy> detectionStudies) {
        this.detectionStudies = detectionStudies;
    }

    public Set<Prescription> getPrescriptions() {
        return this.prescriptions;
    }

    public void setPrescriptions(Set<Prescription> prescriptions) {
        this.prescriptions = prescriptions;
    }

    public User getDoctor() {
        return doctor;
    }

    public void setDoctor(User doctor) {
        this.doctor = doctor;
    }
}
