package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1



/**
 * DetectionStudy generated by hbm2java
 */
public class DetectionStudy  implements java.io.Serializable {


     private Integer detectionStudyId;
     private CaseStudy caseStudy;
     private Detection detection;

    public DetectionStudy() {
    }

    public DetectionStudy(CaseStudy caseStudy, Detection detection) {
       this.caseStudy = caseStudy;
       this.detection = detection;
    }
   
    public Integer getDetectionStudyId() {
        return this.detectionStudyId;
    }
    
    public void setDetectionStudyId(Integer detectionStudyId) {
        this.detectionStudyId = detectionStudyId;
    }
    public CaseStudy getCaseStudy() {
        return this.caseStudy;
    }
    
    public void setCaseStudy(CaseStudy caseStudy) {
        this.caseStudy = caseStudy;
    }
    public Detection getDetection() {
        return this.detection;
    }
    
    public void setDetection(Detection detection) {
        this.detection = detection;
    }




}


