package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DetectionSession generated by hbm2java
 */
public class DetectionSession implements java.io.Serializable {

    private Integer detectionSessionId;
    private Detection detection;
    private String detectionSessionName;
    private Date detectionSessionDate;
    private Double amountPaid;
    private String notes;

    public DetectionSession() {
    }

    public DetectionSession(Integer detectionSessionId, Detection detection, String detectionSessionName, Date detectionSessionDate, Double amountPaid, String notes) {
        this.detectionSessionId = detectionSessionId;
        this.detection = detection;
        this.detectionSessionName = detectionSessionName;
        this.detectionSessionDate = detectionSessionDate;
        this.amountPaid = amountPaid;
        this.notes = notes;
    }

    public Integer getDetectionSessionId() {
        return detectionSessionId;
    }

    public void setDetectionSessionId(Integer detectionSessionId) {
        this.detectionSessionId = detectionSessionId;
    }

    public Detection getDetection() {
        return detection;
    }

    public void setDetection(Detection detection) {
        this.detection = detection;
    }

    public String getDetectionSessionName() {
        return detectionSessionName;
    }

    public void setDetectionSessionName(String detectionSessionName) {
        this.detectionSessionName = detectionSessionName;
    }

    public Date getDetectionSessionDate() {
        return detectionSessionDate;
    }

    public void setDetectionSessionDate(Date detectionSessionDate) {
        this.detectionSessionDate = detectionSessionDate;
    }

    public void setAmountPaid(Double amountPaid) {
        this.amountPaid = amountPaid;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Double getAmountPaid() {
        return amountPaid;
    }

}
