package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private Integer doctorId;
     private String doctorUserName;
     private String doctorUserPassword;
     private String doctorFullName;
     private String doctorMobile;
     private String doctorPhone;
     private String doctorAddress;
     private String doctorEmail;
     private Integer doctorGender;
     private Integer doctorNationalNumber;
     private Date doctorBirthdate;

    public Doctor() {
    }

	
    public Doctor(String doctorUserName, String doctorUserPassword, String doctorFullName, String doctorMobile) {
        this.doctorUserName = doctorUserName;
        this.doctorUserPassword = doctorUserPassword;
        this.doctorFullName = doctorFullName;
        this.doctorMobile = doctorMobile;
    }
    public Doctor(String doctorUserName, String doctorUserPassword, String doctorFullName, String doctorMobile, String doctorPhone, String doctorAddress, String doctorEmail, Integer doctorGender, Integer doctorNationalNumber, Date doctorBirthdate) {
       this.doctorUserName = doctorUserName;
       this.doctorUserPassword = doctorUserPassword;
       this.doctorFullName = doctorFullName;
       this.doctorMobile = doctorMobile;
       this.doctorPhone = doctorPhone;
       this.doctorAddress = doctorAddress;
       this.doctorEmail = doctorEmail;
       this.doctorGender = doctorGender;
       this.doctorNationalNumber = doctorNationalNumber;
       this.doctorBirthdate = doctorBirthdate;
    }
   
    public Integer getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }
    public String getDoctorUserName() {
        return this.doctorUserName;
    }
    
    public void setDoctorUserName(String doctorUserName) {
        this.doctorUserName = doctorUserName;
    }
    public String getDoctorUserPassword() {
        return this.doctorUserPassword;
    }
    
    public void setDoctorUserPassword(String doctorUserPassword) {
        this.doctorUserPassword = doctorUserPassword;
    }
    public String getDoctorFullName() {
        return this.doctorFullName;
    }
    
    public void setDoctorFullName(String doctorFullName) {
        this.doctorFullName = doctorFullName;
    }
    public String getDoctorMobile() {
        return this.doctorMobile;
    }
    
    public void setDoctorMobile(String doctorMobile) {
        this.doctorMobile = doctorMobile;
    }
    public String getDoctorPhone() {
        return this.doctorPhone;
    }
    
    public void setDoctorPhone(String doctorPhone) {
        this.doctorPhone = doctorPhone;
    }
    public String getDoctorAddress() {
        return this.doctorAddress;
    }
    
    public void setDoctorAddress(String doctorAddress) {
        this.doctorAddress = doctorAddress;
    }
    public String getDoctorEmail() {
        return this.doctorEmail;
    }
    
    public void setDoctorEmail(String doctorEmail) {
        this.doctorEmail = doctorEmail;
    }
    public Integer getDoctorGender() {
        return this.doctorGender;
    }
    
    public void setDoctorGender(Integer doctorGender) {
        this.doctorGender = doctorGender;
    }
    public Integer getDoctorNationalNumber() {
        return this.doctorNationalNumber;
    }
    
    public void setDoctorNationalNumber(Integer doctorNationalNumber) {
        this.doctorNationalNumber = doctorNationalNumber;
    }
    public Date getDoctorBirthdate() {
        return this.doctorBirthdate;
    }
    
    public void setDoctorBirthdate(Date doctorBirthdate) {
        this.doctorBirthdate = doctorBirthdate;
    }




}


