package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Patient generated by hbm2java
 */
public class Patient implements java.io.Serializable {

    private Integer patientId;
    private String patientFullName;
    private String patientMobile;
    private String patientPhone;
    private String patientAddress;
    private String patientEmail;
    private Integer patientGender;
    private Integer patientNationalNumber;
    private Date patientBirthdate;
    private String patientJob;
    private Set<Detection> detections = new HashSet<Detection>(0);
    private Set<Reservation> reservations = new HashSet<Reservation>(0);
    private Set<QuestAnswer> questAnswers = new HashSet<QuestAnswer>(0);

    public Patient() {
    }

    public Patient(String patientFullName, String patientMobile) {
        this.patientFullName = patientFullName;
        this.patientMobile = patientMobile;
    }

    public Patient(String patientFullName, String patientMobile, String patientPhone, String patientAddress, String patientEmail, Integer patientGender, Integer patientNationalNumber, Date patientBirthdate, String patientJob, Set<Detection> detections, Set<Reservation> reservations, Set<QuestAnswer> questAnswers) {
        this.patientFullName = patientFullName;
        this.patientMobile = patientMobile;
        this.patientPhone = patientPhone;
        this.patientAddress = patientAddress;
        this.patientEmail = patientEmail;
        this.patientGender = patientGender;
        this.patientNationalNumber = patientNationalNumber;
        this.patientBirthdate = patientBirthdate;
        this.detections = detections;
        this.reservations = reservations;
        this.questAnswers = questAnswers;
        this.patientJob = patientJob;
    }

    public Integer getPatientId() {
        return this.patientId;
    }

    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    public String getPatientFullName() {
        return this.patientFullName;
    }

    public void setPatientFullName(String patientFullName) {
        this.patientFullName = patientFullName;
    }

    public String getPatientMobile() {
        return this.patientMobile;
    }

    public void setPatientMobile(String patientMobile) {
        this.patientMobile = patientMobile;
    }

    public String getPatientPhone() {
        return this.patientPhone;
    }

    public void setPatientPhone(String patientPhone) {
        this.patientPhone = patientPhone;
    }

    public String getPatientAddress() {
        return this.patientAddress;
    }

    public void setPatientAddress(String patientAddress) {
        this.patientAddress = patientAddress;
    }

    public String getPatientEmail() {
        return this.patientEmail;
    }

    public void setPatientEmail(String patientEmail) {
        this.patientEmail = patientEmail;
    }

    public Integer getPatientGender() {
        return this.patientGender;
    }

    public void setPatientGender(Integer patientGender) {
        this.patientGender = patientGender;
    }

    public Integer getPatientNationalNumber() {
        return this.patientNationalNumber;
    }

    public void setPatientNationalNumber(Integer patientNationalNumber) {
        this.patientNationalNumber = patientNationalNumber;
    }

    public Date getPatientBirthdate() {
        return this.patientBirthdate;
    }

    public void setPatientBirthdate(Date patientBirthdate) {
        this.patientBirthdate = patientBirthdate;
    }

    public Set<Detection> getDetections() {
        return this.detections;
    }

    public void setDetections(Set<Detection> detections) {
        this.detections = detections;
    }

    public Set<Reservation> getReservations() {
        return this.reservations;
    }

    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }

    public Set<QuestAnswer> getQuestAnswers() {
        return this.questAnswers;
    }

    public void setQuestAnswers(Set<QuestAnswer> questAnswers) {
        this.questAnswers = questAnswers;
    }

    public String getPatientJob() {
        return patientJob;
    }

    public void setPatientJob(String patientJob) {
        this.patientJob = patientJob;
    }
}
