package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Prescription generated by hbm2java
 */
public class Prescription implements java.io.Serializable {

    private Integer prescriptionId;
    private Concentration concentration;
    private Detection detection;
    private Dose dose;
    private Form form;
    private Medication medication;
    private Date prescriptionDate;
    private User doctor;

    public Prescription() {
    }

    public Prescription(Concentration concentration, Detection detection, Dose dose, Form form, Medication medication, Date prescriptionDate, User doctor) {
        this.concentration = concentration;
        this.detection = detection;
        this.dose = dose;
        this.form = form;
        this.medication = medication;
        this.prescriptionDate = prescriptionDate;
        this.doctor = doctor;
    }

    public Integer getPrescriptionId() {
        return this.prescriptionId;
    }

    public void setPrescriptionId(Integer prescriptionId) {
        this.prescriptionId = prescriptionId;
    }

    public Concentration getConcentration() {
        return this.concentration;
    }

    public void setConcentration(Concentration concentration) {
        this.concentration = concentration;
    }

    public Detection getDetection() {
        return this.detection;
    }

    public void setDetection(Detection detection) {
        this.detection = detection;
    }

    public Dose getDose() {
        return this.dose;
    }

    public void setDose(Dose dose) {
        this.dose = dose;
    }

    public Form getForm() {
        return this.form;
    }

    public void setForm(Form form) {
        this.form = form;
    }

    public Medication getMedication() {
        return this.medication;
    }

    public void setMedication(Medication medication) {
        this.medication = medication;
    }

    public Date getPrescriptionDate() {
        return this.prescriptionDate;
    }

    public void setPrescriptionDate(Date prescriptionDate) {
        this.prescriptionDate = prescriptionDate;
    }

    public User getDoctor() {
        return doctor;
    }

    public void setDoctor(User doctor) {
        this.doctor = doctor;
    }
}
