package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PriceList generated by hbm2java
 */
public class PriceList  implements java.io.Serializable {


     private Integer priceListId;
     private Category category;
     private String priceType;
     private double priceAmount;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public PriceList() {
    }

	
    public PriceList(Category category, String priceType, double priceAmount) {
        this.category = category;
        this.priceType = priceType;
        this.priceAmount = priceAmount;
    }
    public PriceList(Category category, String priceType, double priceAmount, Set<Reservation> reservations) {
       this.category = category;
       this.priceType = priceType;
       this.priceAmount = priceAmount;
       this.reservations = reservations;
    }
   
    public Integer getPriceListId() {
        return this.priceListId;
    }
    
    public void setPriceListId(Integer priceListId) {
        this.priceListId = priceListId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getPriceType() {
        return this.priceType;
    }
    
    public void setPriceType(String priceType) {
        this.priceType = priceType;
    }
    public double getPriceAmount() {
        return this.priceAmount;
    }
    
    public void setPriceAmount(double priceAmount) {
        this.priceAmount = priceAmount;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


