package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Quest generated by hbm2java
 */
public class Quest  implements java.io.Serializable {


     private Integer questId;
     private Category category;
     private String questName;
     private Integer questType;
     private Set<QuestAnswer> questAnswers = new HashSet<QuestAnswer>(0);

    public Quest() {
    }

	
    public Quest(Category category, String questName, Integer questType) {
        this.category = category;
        this.questName = questName;
        this.questType = questType;
    }
    public Quest(Category category, String questName, Integer questType, Set<QuestAnswer> questAnswers) {
       this.category = category;
       this.questName = questName;
       this.questType = questType;
       this.questAnswers = questAnswers;
    }
   
    public Integer getQuestId() {
        return this.questId;
    }
    
    public void setQuestId(Integer questId) {
        this.questId = questId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getQuestName() {
        return this.questName;
    }
    
    public void setQuestName(String questName) {
        this.questName = questName;
    }
    public Integer getQuestType() {
        return this.questType;
    }
    
    public void setQuestType(Integer questType) {
        this.questType = questType;
    }
    public Set<QuestAnswer> getQuestAnswers() {
        return this.questAnswers;
    }
    
    public void setQuestAnswers(Set<QuestAnswer> questAnswers) {
        this.questAnswers = questAnswers;
    }




}


