package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Session generated by hbm2java
 */
public class Session  implements java.io.Serializable {


     private Integer sessionId;
     private Detection detection;
     private String sessionName;
     private Date sessionDate;
     private Double amountPaid;
     private String notes;

    public Session() {
    }

	
    public Session(Detection detection, String sessionName, Date sessionDate, Double amountPaid) {
        this.detection = detection;
        this.sessionName = sessionName;
        this.sessionDate = sessionDate;
        this.amountPaid = amountPaid;
    }
    public Session(Detection detection, String sessionName, Date sessionDate, Double amountPaid, String notes) {
       this.detection = detection;
       this.sessionName = sessionName;
       this.sessionDate = sessionDate;
       this.amountPaid = amountPaid;
       this.notes = notes;
    }
   
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }
    public Detection getDetection() {
        return this.detection;
    }
    
    public void setDetection(Detection detection) {
        this.detection = detection;
    }
    public String getSessionName() {
        return this.sessionName;
    }
    
    public void setSessionName(String sessionName) {
        this.sessionName = sessionName;
    }
    public Date getSessionDate() {
        return this.sessionDate;
    }
    
    public void setSessionDate(Date sessionDate) {
        this.sessionDate = sessionDate;
    }
    public Double getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(Double amountPaid) {
        this.amountPaid = amountPaid;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


