package com.os.models;
// Generated Jan 12, 2016 5:08:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String userPassword;
     private int userType;
     private String userFullName;
     private String userMobile;
     private String userPhone;
     private String userAddress;
     private String userEmail;
     private Integer userGender;
     private Integer userNationalNumber;
     private Date userBirthdate;

    public User() {
    }

	
    public User(String userName, String userPassword, int userType, String userFullName, String userMobile) {
        this.userName = userName;
        this.userPassword = userPassword;
        this.userType = userType;
        this.userFullName = userFullName;
        this.userMobile = userMobile;
    }
    public User(String userName, String userPassword, int userType, String userFullName, String userMobile, String userPhone, String userAddress, String userEmail, Integer userGender, Integer userNationalNumber, Date userBirthdate) {
       this.userName = userName;
       this.userPassword = userPassword;
       this.userType = userType;
       this.userFullName = userFullName;
       this.userMobile = userMobile;
       this.userPhone = userPhone;
       this.userAddress = userAddress;
       this.userEmail = userEmail;
       this.userGender = userGender;
       this.userNationalNumber = userNationalNumber;
       this.userBirthdate = userBirthdate;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public int getUserType() {
        return this.userType;
    }
    
    public void setUserType(int userType) {
        this.userType = userType;
    }
    public String getUserFullName() {
        return this.userFullName;
    }
    
    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName;
    }
    public String getUserMobile() {
        return this.userMobile;
    }
    
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public Integer getUserGender() {
        return this.userGender;
    }
    
    public void setUserGender(Integer userGender) {
        this.userGender = userGender;
    }
    public Integer getUserNationalNumber() {
        return this.userNationalNumber;
    }
    
    public void setUserNationalNumber(Integer userNationalNumber) {
        this.userNationalNumber = userNationalNumber;
    }
    public Date getUserBirthdate() {
        return this.userBirthdate;
    }
    
    public void setUserBirthdate(Date userBirthdate) {
        this.userBirthdate = userBirthdate;
    }




}


